# Site settings
title: TNQZ
description: "TN QAZAQ company site"
url: "https://tnqz.tech/"

# User settings
username: TN&nbsp;QAZAQ

email: "TN QAZAQ <maill@tnqz.tech>"
telegram_account: https://t.me/tnqazaq
linkedin_group: https://www.linkedin.com/company/tnqz
facebook_group: https://www.facebook.com/groups/tnqz.tech
vk_group: https://vk.com/tnqz.tech

# Google-analytics
google-analytics:
  id: "G-XJ6E4PY561"

exclude: ['package.json', 'src' , 'node_modules']
