# Site settings
title: TNQZ
description: TN QAZAQ company site
url: "localhost:4000"

# User settings
username: TN QAZAQ
user_description: IT staffing for your business IT staffing for your business IT staffing for your business
user_title: IT staffing for your business
email: social@tnqz.tech
github_username: tnqz
linkedin_username: tnqz
facebook_username: tnqz.tech
vk_username: tnqz.tech
telegram_username: tnqazaq

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
