# Site settings
title: TNQZ
description: TN QAZAQ company site
url: "https://tnqz.github.io/"

# User settings
username: TN&nbsp;QAZAQ
user_description: IT staffing for your business IT staffing for your business IT staffing for your business
user_title: IT staffing for your business

email: "TN QAZAQ <social@tnqz.tech>"
telegram_account: https://t.me/tnqazaq
linkedin_group: https://www.linkedin.com/company/tnqz
facebook_group: https://www.facebook.com/groups/tnqz.tech
vk_group: https://vk.com/tnqz.tech

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
