# Site settings
title: TNQZ
description: "TNQZ company site"
url: "https://tnqz.tech/"

# User settings
username: TNQZ LLC

email: "mail@tnqz.tech"
telegram_account: tnqz_bot
linkedin_group: https://www.linkedin.com/company/tnqz
facebook_group: https://www.facebook.com/groups/tnqz.tech

# Google-analytics
google-analytics:
  id: "G-XJ6E4PY561"

exclude: ['package.json', 'src' , 'node_modules']
